# Generated by Django 4.2.6 on 2023-10-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anime_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('ended', models.BooleanField()),
                ('awards', models.CharField(max_length=200)),
                ('content_rating', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='', null=True, upload_to='images/')),
            ],
        ),
    ]
