# Generated by Django 4.2.6 on 2023-10-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_anime_info_updated_at_anime_info_airday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('img', models.TextField()),
                ('cropped_img', models.TextField()),
                ('is_adult', models.BooleanField(default=False)),
                ('genres', models.JSONField()),
                ('medium', models.CharField(max_length=255)),
                ('distributed_air_time', models.CharField(max_length=255)),
                ('is_laftel_only', models.BooleanField(default=False)),
                ('is_uncensored', models.BooleanField(default=False)),
                ('is_dubbed', models.BooleanField(default=False)),
                ('is_avod', models.BooleanField(default=False)),
                ('avod_status', models.CharField(max_length=255)),
                ('is_viewing', models.BooleanField(default=True)),
                ('latest_episode_created', models.DateTimeField()),
                ('latest_published_datetime', models.DateTimeField()),
                ('is_episode_existed', models.BooleanField(default=True)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
